### ISSUE TITLE
Avoid using the "Natural" name

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/wakarusa#2]
As of GHC 7.10, `Numeric.Natural` is a part of `base`, and it exports a numeric type named `Natural`, which could potentially create lots of naming conflicts with `wakarusa`'s `Natural`. We may want to rename `Natural f g` to something like `f :~> g` (idea taken from ekmett's [`indexed` package](https://github.com/ekmett/indexed/blob/cf1c5683284f422bfca8956947c11410bc9d9e1b/src/Indexed/Types.hs#L60)).

**Comment by andygill** [comment]
I wondered about the same thing. Though there is enough to learn already without using type symbols.

`:~>`, `:=>`, `:->:`, and `:*->*:` are possibles.

**Comment by RyanGlScott** [comment]
I mean, we don't _have_ to use a type operator, but it does seem like a nice way to indicate its "functionality".

From a human-parser POV, I feel like `:->` or `:=>` could be easily mistaken for `->` or `=>` if you're not squinting. I'd be okay with `:~>`, or with `:*->*:` if we want to pun on its kind (although technically its kind is `(k -> *) -> (k -> *) -> *` if you have `PolyKinds` on :P).

**Comment by andygill** [comment]
You're right. With PolyKinds, we get the richer type.

**Comment by andygill** [comment]
Possible names include Morphism or FunctorMorphism. But (from wikipedia) "In a functor category, the morphisms are natural transformations."

**Comment by superfunc** [comment]
FunctorMorphism would probably be best

**Comment by andygill** [comment]
@ ekmett uses `~>` and `:~>`

https://github.com/ekmett/indexed/blob/master/src/Indexed/Types.hs

**Comment by andygill** [comment]
@RyanGlScott, can you merge the wakarusa and @ekmett's implementation into a single (small) repo, ku-fpg/natural-transformation. Thanks. We'll mangle it a bit more, then push to hackage to put our foot in the door.

**Comment by superfunc** [comment]
What about ```#->```. It's a little noisier, but its distinct.

**Comment by andygill** [comment]
It needs to start with `:`, because its a type constructor. Though I like `#->`, because we use `#` as our application combinator.

**Comment by superfunc** [comment]
edit: Previous post was deleted. In it I suggested using `#->` as a type constructor. 

Ah, ok. Whatever is decided, I think should be limited to three characters for operators, anything else is too much syntactic noise.

**Comment by ekmett** [comment]
@andygill: The rules around type constructor names changed back around 7.4 or so.

You can make a

```
type f ~> g = forall a. f a -> g a
```

just fine now.

Why did this happen? They wanted to be able to use `(+)` and `(*)` for the type families for Iavor's work on type level nats.

This killed the old occasional use of binding type variables to symbols, which was common for definitions like:

``` haskell
    id :: Category (~>) => a ~> a
    (.) :: Category (~>) => (b ~> c) -> (a ~> b) -> a ~> c 
```

So now they have to use a normal alphanumeric identifier.

**Comment by ekmett** [comment]
You still need :'s for data constructors though.

**Comment by RyanGlScott** [comment]
I've reopened this in the [`natural-transformation`](https://github.com/ku-fpg/natural-transformation/issues/2) repo.
